prueba-commit
NicolasSMoralesRomero/Prueba-pagina-google pull request #2
Opened 2023-07-27 18:24 UTC by NicolasSMoralesRomero

Buenas tardes.
Cargo lo solicitado en el tkt.
Gracias

2023-07-27 18:31 UTC, juliofranco9111 requested changes
Faltaría linkear el archivo .css dentro del archivo .html

2023-07-30 17:11 UTC, NicolasSMoralesRomero commented
Buenas tardes.

Ya hice los cambios solicitados.
![image](https://github.com/NicolasSMoralesRomero/Prueba-pagina-google/assets/79733332/a396ac5c-0c3f-4695-bc37-3fe063789be3)

![image](https://github.com/NicolasSMoralesRomero/Prueba-pagina-google/assets/79733332/65056137-41c8-4405-9994-f8308e2cbe7b)

Abrazo!

2023-08-01 05:39 UTC, juliofranco9111 commented on Pureba de pagina 1/index.html
> +    <link rel="stylesheet" type="text/css" href="CSS/styles.css" />
mejor que quede href="./CSS/styles.css", cambiando eso ya podes mergear

2023-08-01 05:39 UTC, juliofranco9111 approved these changes
Buenaaa

2023-08-01 17:40 UTC, merged